{
    "name": "CS Patient Followup Forms",
    "version": "19.0.1.0.0",
    "summary": "Plantillas dinamicas para seguimiento de pacientes",
    "category": "Healthcare",
    "author": "Cositt Technologies",
    "website": "https://www.cositt.com",
    "license": "LGPL-3",
    "icon": "/cs_patient_followup_forms/static/icon.png",
    "images": ["static/icon.png"],
    "depends": ["base", "mail", "contacts"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/followup_template_views.xml",
        "views/followup_assessment_views.xml",
        "views/res_partner_views.xml",
        "wizards/add_field_wizard_views.xml",
        "wizards/guided_answer_wizard_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
}
